# Generated by Django 5.0.6 on 2024-06-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorAccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walls', models.BooleanField(default=False)),
                ('windows', models.BooleanField(default=False)),
                ('roof', models.BooleanField(default=False)),
                ('occupants', models.BooleanField(default=False)),
                ('equipments', models.BooleanField(default=False)),
                ('role_name', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Calculator Access Roles',
                'ordering': ['role_name'],
                'unique_together': {('walls', 'windows', 'roof', 'occupants', 'equipments')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='calc_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.calculatoraccessrole'),
        ),
    ]
