# Generated by Django 5.0.6 on 2024-07-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_calculatoraccessrole_customuser_calc_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forgot_otp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forgot_password_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_update_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
